### ISSUE TITLE
Delay causeed by Notification

### ISSUE THREAD

**Issue by ryanwooa** [zli213/TaskTick#72]
![image](https://github.com/zli213/SynergyStudy/assets/119087910/cf43de5a-7528-46ae-a53f-694fefae0bf7)
After change the date in Schedular, It need wait for 'notification time' to  make the change happen, Schedular card close and the date shown in SingleItem change.

THE CHANGE SHOULD HAPPEN IMMEDIATELY. Only the notification should wait for the time, not the Schedular and SingleItem.
Plz fix.
@zli213

**Comment by ryanwooa** [comment]
Another question:
When I at a Project page, and  edit a task, it will notify that add a task in this project. But it already in it. So the notification is not needed.

**Comment by ryanwooa** [comment]
Another question:
While I am adding new task, I click the schedular, it will have notification and close the TaskEditor.
I can not add task

**Comment by zli213** [comment]
I see you are currently posting "fix this issue". Do I still need to continue looking into these bugs, or have you already resolved them?

**Comment by ryanwooa** [comment]
I solved these today, so you do not need to looking them.
